In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dataset.csv")
df.head()

,id,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,Male,24.443011,1.699998,81.669950,yes,yes,2.000000,2.983297,Sometimes,no,2.763573,no,0.000000,0.976473,Sometimes,Public_Transportation,Overweight_Level_II
1,1,Female,18.000000,1.560000,57.000000,yes,yes,2.000000,3.000000,Frequently,no,2.000000,no,1.000000,1.000000,no,Automobile,Normal_Weight
2,2,Female,18.000000,1.711460,50.165754,yes,yes,1.880534,1.411685,Sometimes,no,1.910378,no,0.866045,1.673584,no,Public_Transportation,Insufficient_Weight
3,3,Female,20.952737,1.710730,131.274851,yes,yes,3.000000,3.000000,Sometimes,no,1.674061,no,1.467863,0.780199,Sometimes,Public_Transportation,Obesity_Type_III
4,4,Male,31.641081,1.914186,93.798055,yes,yes,2.679664,1.971472,Sometimes,no,1.979848,no,1.967973,0.931721,Sometimes,Public_Transportation,Overweight_Level_II

In [3]:
df["NObeyesdad"].value_counts()

NObeyesdad
Obesity_Type_III       4046
Obesity_Type_II        3248
Normal_Weight          3082
Obesity_Type_I         2910
Insufficient_Weight    2523
Overweight_Level_II    2522
Overweight_Level_I     2427
Name: count, dtype: int64

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20758 non-null  int64
 1   Gender                          20758 non-null  str
 2   Age                             20758 non-null  float64
 3   Height                          20758 non-null  float64
 4   Weight                          20758 non-null  float64
 5   family_history_with_overweight  20758 non-null  str
 6   FAVC                            20758 non-null  str
 7   FCVC                            20758 non-null  float64
 8   NCP                             20758 non-null  float64
 9   CAEC                            20758 non-null  str
 10  SMOKE                           20758 non-null  str
 11  CH2O                            20758 non-null  float64
 12  SCC                             20758 non-null  str
 13  FAF                             20758 non-null  float64
 14  TUE                             20758 non-null  float64
 15  CALC                            20758 non-null  str
 16  MTRANS                          20758 non-null  str
 17  NObeyesdad                      20758 non-null  str
dtypes: float64(8), int64(1), str(9)
memory usage: 2.9 MB

In [5]:
df.select_dtypes(include=["object", "string"]).columns

Index(['Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE',
       'SCC', 'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='str')

In [6]:
X = df.drop("NObeyesdad", axis=1)
y = df["NObeyesdad"]

<h4>Encoding both x,y :</h4>

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_encoded = le.fit_transform(y) #we encode the y which is our target column (label encoding)

In [8]:
dict(zip(le.classes_, le.transform(le.classes_)))

{'Insufficient_Weight': np.int64(0),
 'Normal_Weight': np.int64(1),
 'Obesity_Type_I': np.int64(2),
 'Obesity_Type_II': np.int64(3),
 'Obesity_Type_III': np.int64(4),
 'Overweight_Level_I': np.int64(5),
 'Overweight_Level_II': np.int64(6)}

In [9]:
df["MTRANS"].unique() #i do this for "CAEC" and "CALC" to check how many unique elements it has for one hot encoding

<StringArray>
['Public_Transportation', 'Automobile', 'Walking', 'Motorbike', 'Bike']
Length: 5, dtype: str

In [10]:
X_encoded = pd.get_dummies(X, drop_first=False)

In [11]:
X_encoded.head()

,id,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE,Gender_Female,...,SCC_no,SCC_yes,CALC_Frequently,CALC_Sometimes,CALC_no,MTRANS_Automobile,MTRANS_Bike,MTRANS_Motorbike,MTRANS_Public_Transportation,MTRANS_Walking
0,0,24.443011,1.699998,81.669950,2.000000,2.983297,2.763573,0.000000,0.976473,False,...,True,False,False,True,False,False,False,False,True,False
1,1,18.000000,1.560000,57.000000,2.000000,3.000000,2.000000,1.000000,1.000000,True,...,True,False,False,False,True,True,False,False,False,False
2,2,18.000000,1.711460,50.165754,1.880534,1.411685,1.910378,0.866045,1.673584,True,...,True,False,False,False,True,False,False,False,True,False
3,3,20.952737,1.710730,131.274851,3.000000,3.000000,1.674061,1.467863,0.780199,True,...,True,False,False,True,False,False,False,False,True,False
4,4,31.641081,1.914186,93.798055,2.679664,1.971472,1.979848,1.967973,0.931721,False,...,True,False,False,True,False,False,False,False,True,False

In [12]:
X.head()

,id,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,0,Male,24.443011,1.699998,81.669950,yes,yes,2.000000,2.983297,Sometimes,no,2.763573,no,0.000000,0.976473,Sometimes,Public_Transportation
1,1,Female,18.000000,1.560000,57.000000,yes,yes,2.000000,3.000000,Frequently,no,2.000000,no,1.000000,1.000000,no,Automobile
2,2,Female,18.000000,1.711460,50.165754,yes,yes,1.880534,1.411685,Sometimes,no,1.910378,no,0.866045,1.673584,no,Public_Transportation
3,3,Female,20.952737,1.710730,131.274851,yes,yes,3.000000,3.000000,Sometimes,no,1.674061,no,1.467863,0.780199,Sometimes,Public_Transportation
4,4,Male,31.641081,1.914186,93.798055,yes,yes,2.679664,1.971472,Sometimes,no,1.979848,no,1.967973,0.931721,Sometimes,Public_Transportation

In [13]:
X_encoded = X_encoded.astype(int)

In [14]:
X_encoded.head()

,id,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE,Gender_Female,...,SCC_no,SCC_yes,CALC_Frequently,CALC_Sometimes,CALC_no,MTRANS_Automobile,MTRANS_Bike,MTRANS_Motorbike,MTRANS_Public_Transportation,MTRANS_Walking
0,0,24,1,81,2,2,2,0,0,0,...,1,0,0,1,0,0,0,0,1,0
1,1,18,1,57,2,3,2,1,1,1,...,1,0,0,0,1,1,0,0,0,0
2,2,18,1,50,1,1,1,0,1,1,...,1,0,0,0,1,0,0,0,1,0
3,3,20,1,131,3,3,1,1,0,1,...,1,0,0,1,0,0,0,0,1,0
4,4,31,1,93,2,1,1,1,0,0,...,1,0,0,1,0,0,0,0,1,0

In [15]:
X_encoded = pd.get_dummies(X, drop_first=False, dtype=int)
X_encoded.head()

,id,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE,Gender_Female,...,SCC_no,SCC_yes,CALC_Frequently,CALC_Sometimes,CALC_no,MTRANS_Automobile,MTRANS_Bike,MTRANS_Motorbike,MTRANS_Public_Transportation,MTRANS_Walking
0,0,24.443011,1.699998,81.669950,2.000000,2.983297,2.763573,0.000000,0.976473,0,...,1,0,0,1,0,0,0,0,1,0
1,1,18.000000,1.560000,57.000000,2.000000,3.000000,2.000000,1.000000,1.000000,1,...,1,0,0,0,1,1,0,0,0,0
2,2,18.000000,1.711460,50.165754,1.880534,1.411685,1.910378,0.866045,1.673584,1,...,1,0,0,0,1,0,0,0,1,0
3,3,20.952737,1.710730,131.274851,3.000000,3.000000,1.674061,1.467863,0.780199,1,...,1,0,0,1,0,0,0,0,1,0
4,4,31.641081,1.914186,93.798055,2.679664,1.971472,1.979848,1.967973,0.931721,0,...,1,0,0,1,0,0,0,0,1,0

In [16]:
sorted(set(y_encoded))

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6)]

Im now splitting the data into testing and training
1) testing - 20%
2) training - 80% 

the names suggest exactly what they do.

stratify=y_encoded;
what this does -> we take the testing dataset also to have the same ratio as our target column 
say we have 1.5x of obesity type1 in the given data so for testing we maintain the same ratio of 1.5x to make our model output more reliable

In [17]:
X_encoded.shape, y_encoded.shape

((20758, 31), (20758,))

In [18]:
import pickle

with open("processed_data.pkl", "wb") as f:
    pickle.dump((X_encoded, y_encoded), f)

Continue from loading the preprocessed data.

In [19]:
import pickle

with open("processed_data.pkl", "rb") as f:
    X_encoded, y_encoded = pickle.load(f)

X_encoded.shape, y_encoded.shape

((20758, 31), (20758,))

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

X_train.shape, X_test.shape

#now we make the test and train split before traning the classifier

((16606, 31), (4152, 31))

In [21]:
#training the first decision tree (this is before moving on to random forest.)
from sklearn.tree import DecisionTreeClassifier

# Create model
dt = DecisionTreeClassifier(random_state=42)

# Train model
dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [22]:
#now we test the accuracy (real evaluation of the first tree), ie by making predictions
y_pred = dt.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy (Decision Tree):", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy (Decision Tree): 0.845616570327553

Classification Report:

              precision    recall  f1-score   support

           0       0.90      0.89      0.90       505
           1       0.78      0.82      0.80       617
           2       0.82      0.80      0.81       582
           3       0.94      0.95      0.94       650
           4       0.99      0.99      0.99       809
           5       0.66      0.65      0.65       485
           6       0.72      0.70      0.71       504

    accuracy                           0.85      4152
   macro avg       0.83      0.83      0.83      4152
weighted avg       0.85      0.85      0.85      4152

In [24]:
#we move to random forest now:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 0.8978805394990366

Classification Report:

              precision    recall  f1-score   support

           0       0.93      0.93      0.93       505
           1       0.83      0.87      0.85       617
           2       0.89      0.90      0.89       582
           3       0.97      0.97      0.97       650
           4       1.00      1.00      1.00       809
           5       0.80      0.72      0.76       485
           6       0.79      0.81      0.80       504

    accuracy                           0.90      4152
   macro avg       0.89      0.89      0.89      4152
weighted avg       0.90      0.90      0.90      4152

Decision tree --> 85%
Random Forest --> 89% 

~5% jump.

In [25]:
#now we move on to boosting (where a new model learns from the errors of the previous one)
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report

print("Gradient Boosting Accuracy:", accuracy_score(y_test, y_pred_gb))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_gb))

Gradient Boosting Accuracy: 0.9063102119460501

Classification Report:

              precision    recall  f1-score   support

           0       0.94      0.95      0.94       505
           1       0.87      0.89      0.88       617
           2       0.88      0.90      0.89       582
           3       0.97      0.97      0.97       650
           4       1.00      1.00      1.00       809
           5       0.82      0.75      0.79       485
           6       0.80      0.81      0.80       504

    accuracy                           0.91      4152
   macro avg       0.90      0.90      0.90      4152
weighted avg       0.91      0.91      0.91      4152

</h3> Now we start the voting implementation </h3>

In [26]:
#1. Hard voting here we just see the class most models have predicted.
from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

dt = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(n_estimators=100, random_state=42)
gb = GradientBoostingClassifier(random_state=42)

voting_hard = VotingClassifier(
    estimators=[("dt", dt), ("rf", rf), ("gb", gb)],
    voting="hard"
)

voting_hard.fit(X_train, y_train)
y_pred_hard = voting_hard.predict(X_test)

print("Hard Voting Accuracy:", accuracy_score(y_test, y_pred_hard))
print(classification_report(y_test, y_pred_hard))

#after running -> expected results.

Hard Voting Accuracy: 0.8995664739884393
              precision    recall  f1-score   support

           0       0.93      0.95      0.94       505
           1       0.85      0.88      0.87       617
           2       0.88      0.90      0.89       582
           3       0.97      0.97      0.97       650
           4       1.00      1.00      1.00       809
           5       0.81      0.73      0.77       485
           6       0.79      0.79      0.79       504

    accuracy                           0.90      4152
   macro avg       0.89      0.89      0.89      4152
weighted avg       0.90      0.90      0.90      4152

In [27]:
#soft voting -> average probablitites
voting_soft = VotingClassifier(
    estimators=[("dt", dt), ("rf", rf), ("gb", gb)],
    voting="soft"
)

voting_soft.fit(X_train, y_train)
y_pred_soft = voting_soft.predict(X_test)

print("Soft Voting Accuracy:", accuracy_score(y_test, y_pred_soft))
print(classification_report(y_test, y_pred_soft))

Soft Voting Accuracy: 0.8798169556840078
              precision    recall  f1-score   support

           0       0.92      0.94      0.93       505
           1       0.83      0.85      0.84       617
           2       0.85      0.86      0.85       582
           3       0.96      0.96      0.96       650
           4       1.00      1.00      1.00       809
           5       0.74      0.69      0.71       485
           6       0.76      0.77      0.77       504

    accuracy                           0.88      4152
   macro avg       0.87      0.87      0.87      4152
weighted avg       0.88      0.88      0.88      4152

In [28]:
#weighted soft voting -> gives influence to better models
voting_weighted = VotingClassifier(
    estimators=[("dt", dt), ("rf", rf), ("gb", gb)],
    voting="soft",
    weights=[1, 2, 3]   # dt, rf, gb
)

voting_weighted.fit(X_train, y_train)
y_pred_weighted = voting_weighted.predict(X_test)

print("Weighted Soft Voting Accuracy:", accuracy_score(y_test, y_pred_weighted))
print(classification_report(y_test, y_pred_weighted))

Weighted Soft Voting Accuracy: 0.9022157996146436
              precision    recall  f1-score   support

           0       0.93      0.96      0.95       505
           1       0.88      0.88      0.88       617
           2       0.88      0.89      0.88       582
           3       0.97      0.97      0.97       650
           4       1.00      1.00      1.00       809
           5       0.80      0.74      0.77       485
           6       0.79      0.81      0.80       504

    accuracy                           0.90      4152
   macro avg       0.89      0.89      0.89      4152
weighted avg       0.90      0.90      0.90      4152

In [ ]:
# summary of voting:-
# dt : 0.845616570327553
# rf : 0.8978805394990366
# gb : 0.9063102119460501
# hard : 0.8995664739884393
# soft : 0.8798169556840078
# soft weighted : 0.9022157996146436

# expected, except for hard and soft which may sometimes differ.

In [29]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

# Base models
dt = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(n_estimators=100, random_state=42)
gb = GradientBoostingClassifier(random_state=42)

stack = StackingClassifier(
    estimators=[
        ("dt", dt),
        ("rf", rf),
        ("gb", gb)
    ],
    final_estimator=LogisticRegression(max_iter=2000),
    cv=5
)

stack.fit(X_train, y_train)

y_pred_stack = stack.predict(X_test)

print("Stacking Accuracy:", accuracy_score(y_test, y_pred_stack))
print(classification_report(y_test, y_pred_stack))

Stacking Accuracy: 0.9075144508670521
              precision    recall  f1-score   support

           0       0.94      0.95      0.95       505
           1       0.88      0.88      0.88       617
           2       0.88      0.91      0.89       582
           3       0.97      0.96      0.97       650
           4       1.00      1.00      1.00       809
           5       0.81      0.76      0.78       485
           6       0.80      0.82      0.81       504

    accuracy                           0.91      4152
   macro avg       0.90      0.90      0.90      4152
weighted avg       0.91      0.91      0.91      4152

In [30]:
#lets implement blending now (does not have cv, like we had 5 fold cv in stacking)
#this uses a "test" data set from the already existing train data.

#step 1- creating the split
from sklearn.model_selection import train_test_split

X_train_blend, X_val_blend, y_train_blend, y_val_blend = train_test_split(
    X_train, y_train,
    test_size=0.2,
    random_state=42,
    stratify=y_train
)

In [31]:
#step2 -> training the models on this created "test split"
dt.fit(X_train_blend, y_train_blend)
rf.fit(X_train_blend, y_train_blend)
gb.fit(X_train_blend, y_train_blend)

GradientBoostingClassifier(random_state=42)

In [32]:
#testing the model for the validation set(what the model created)
import numpy as np

val_preds = np.column_stack([
    dt.predict_proba(X_val_blend),
    rf.predict_proba(X_val_blend),
    gb.predict_proba(X_val_blend)
])

meta_model = LogisticRegression(max_iter=2000)
meta_model.fit(val_preds, y_val_blend)

LogisticRegression(max_iter=2000)

In [33]:
test_preds = np.column_stack([
    dt.predict_proba(X_test),
    rf.predict_proba(X_test),
    gb.predict_proba(X_test)
])

y_pred_blend = meta_model.predict(test_preds)

print("Blending Accuracy:", accuracy_score(y_test, y_pred_blend))
print(classification_report(y_test, y_pred_blend))

Blending Accuracy: 0.9072736030828517
              precision    recall  f1-score   support

           0       0.93      0.96      0.95       505
           1       0.89      0.88      0.88       617
           2       0.87      0.90      0.89       582
           3       0.97      0.96      0.97       650
           4       1.00      1.00      1.00       809
           5       0.83      0.76      0.79       485
           6       0.80      0.82      0.81       504

    accuracy                           0.91      4152
   macro avg       0.90      0.90      0.90      4152
weighted avg       0.91      0.91      0.91      4152

we see blending ~ stacking which is expected. we had so much data approx 20k rows so that stacking had a good enough validation dataset, to produce a good result.

In [34]:
#before doing this expt -> rf uses no max depth by default (so i expect rf_shallow to not be high in accuracy)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

rf_shallow = RandomForestClassifier(
    n_estimators=200,
    max_depth=5,         
    random_state=42,
    n_jobs=-1
)

rf_deep = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,       
    random_state=42,
    n_jobs=-1
)

# Train
rf_shallow.fit(X_train, y_train)
rf_deep.fit(X_train, y_train)

# Predict
y_pred_shallow = rf_shallow.predict(X_test)
y_pred_deep = rf_deep.predict(X_test)

# Evaluate
print("RF Shallow Accuracy:", accuracy_score(y_test, y_pred_shallow))
print(classification_report(y_test, y_pred_shallow))

print("\n")

print("RF Deep Accuracy:", accuracy_score(y_test, y_pred_deep))
print(classification_report(y_test, y_pred_deep))

#after expriment -> valid ~10% inc in accuracy.

RF Shallow Accuracy: 0.8090077071290944
              precision    recall  f1-score   support

           0       0.88      0.89      0.88       505
           1       0.62      0.85      0.72       617
           2       0.74      0.81      0.78       582
           3       0.91      0.97      0.94       650
           4       0.99      1.00      0.99       809
           5       0.80      0.32      0.46       485
           6       0.70      0.63      0.66       504

    accuracy                           0.81      4152
   macro avg       0.81      0.78      0.78      4152
weighted avg       0.82      0.81      0.80      4152



RF Deep Accuracy: 0.8935452793834296
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       505
           1       0.83      0.88      0.85       617
           2       0.88      0.88      0.88       582
           3       0.97      0.97      0.97       650
           4       1.00      1.00      1.00       809
           5       0.79      0.72      0.75       485
           6       0.78      0.79      0.79       504

    accuracy                           0.89      4152
   macro avg       0.88      0.88      0.88      4152
weighted avg       0.89      0.89      0.89      4152